GET http://127.0.0.1:30007/tasks


##############################
POST http://localhost:30007/tasks
Content-Type: application/json

{
    "title":"Kubernetes Kurulumunu tamamla"
}


##############################
PATCH  http://localhost:30007/tasks/1
Content-Type: application/json

{
    "title":"Kubernetes Kurulumunu tamamla (edited)",
    "completed":true
}