name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:


      - name: Create Kind cluster
        run: |
          kind create cluster --name my-cluster

      - name: Load Docker image into Kind
        run: |
          kind load docker-image hilmiemel/todo-list-backend:latest --name my-cluster

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Check services and pods
        run: |
          kubectl get po,svc
          
