name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/kind


    - name: Create Kubernetes cluster
      run: |
        kind create cluster --name kind

    - name: Build and Push Docker Image
      run: |
        docker build -t todo-list-app .
        kind load docker-image todo-list-app

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
