name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:


      - name: Create Kind cluster
        run: |
          kind delete cluster
          kind create cluster

      - name: Load Docker image into Kind
        run: |
          kind load docker-image hilmiemel/todo-list-backend:latest
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Check  pods
        run: |
          kubectl get pods -owide
      
      - name: Check  services
        run: |
          kubectl get svc -owide
